### ISSUE TITLE
Auto-fill only parts of a transaction and let the rest get entered manually

### ISSUE THREAD

**Issue by varac** [MoritzR/fints2ledger#25]
I have some use-cases for auto-filling i.e. only the payee, but I still want to enter the purpose manually.
To my knowledge this is not possible now, right ?
If I add a match rule it will override the `fill:` keys and leave those as the original values, but don't give me the opportunity to manual enter anz value. Or am i wrong ? Hope it gets clear what I want.

**Comment by MoritzR** [comment]
This is not too well documented but is mentioned [here](https://github.com/MoritzR/fints2ledger/issues/5#issuecomment-821950699) and in the [Changelog](https://github.com/MoritzR/fints2ledger/blob/master/CHANGELOG.md#080), if I understand you correctly.
Example:
```
    - match:
        payee: "MUSIC COMPANY 123"
      fill:
        credit_account: "expenses:monthly:musiccompany"
        purpose: 
```
will auto fill `credit_account` and prompt for `purpose`
