### ISSUE TITLE
FR: Ability to auto-match transactions

### ISSUE THREAD

**Issue by varac** [MoritzR/fints2ledger#5]
[buchhaltung](https://github.com/johannesgerer/buchhaltung) has a `Semi-automatically match transactions to accounts using Bayesian classification`. It didn't work too well for me but still it's suggestions were 75% right.

I'd be in favor of a config file auto automatic matching/suggestions like shown in the https://github.com/jamatute/beancount-importer README:

```
- regexp: '.*RISEUP.*'
  account: 'Expenses:Bills:Email'
  payee: 'Riseup'
  description: 'Donation to Riseup'
```

**Comment by MoritzR** [comment]
Good suggestion! I have kind of wanted something like this myself but never found enough reason to implement it.
I tested a bit and found the most usable version for me was to automatically match fields, so that entire entries can be skipped without having to confirm a suggestion.

I updated the readme at https://github.com/MoritzR/fints2ledger#automatically-matching-transactions

I am interested to know how that works for you.

**Comment by varac** [comment]
Works super well, much better than buchhaltung.
The only feature i'm missing is automatically accepting original fields.

If I have this matching rule:

```
- match:                                                             
    payee: "My Bank"
    purpose: ".*monthly fee.*"                                  
  fill:                                                              
    credit_account: "Expenses:Bank"
 ```

I will always be asked for the `purpose`, which I can accept with hitting enter.
But I'd like to auto-accept the `purpose` in this case, so sth like this would be awesome:

```
- match:                                                             
    payee: "My Bank"
    purpose: ".*monthly fee.*"                                  
  fill:                                                              
    credit_account: "Expenses:Bank"
    purpose: "ORIGINAL"
```

Or whoever the keyword should be named to indicate to accept the original purpose.
